### ISSUE TITLE
Compatiblity issues with Python3

### ISSUE THREAD

**Issue by supermeisi** [sommer/papertimer#1]
Thank you very much for the great effort in programming this timer. I have used it several times in various conferences. Unfortunately, it does not work anymore with Python3, since it leads to many errors, even after updating the naming scheme of the new packages. Is there still any work going on in this project?

**Comment by sommer** [comment]
I've pushed an update for Python 3 as sommer/papertimer@d4d15e860898bd3d31ee8b7919723e98e332b493
